language: python

python:
  - 3.3
  - 3.4

env:
  - DJANGO=Django==1.7.1
  - DJANGO=https://github.com/django/django/archive/master.zip

matrix:
  # 2014-11-16: global failure due to django-nose failure
  allow_failures:
    - env: DJANGO=https://github.com/django/django/archive/master.zip

install:
  - sudo apt-get install libxml2-dev libxslt-dev
  - pip install $DJANGO
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install -r requirements-doc.txt

script:
  - mkdocs build
  - cd tests
  - coverage run --source=django_google_dork --omit=*/migrations/* ./manage.py test

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.3* && $DJANGO == 1.7* ]]; then coveralls; fi
