language: python

python:
  - 3.3
  - 3.4

install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt

script:
  coverage run --source=moscowdjango,meetup manage.py test

after_success:
  coveralls
