language: python

python:
  - 3.3
  - 3.4

env:
  - DJANGO=Django==1.7.1
  - DJANGO=https://github.com/django/django/archive/master.zip

matrix:
  # 2014-11-16: global failure due to django-nose failure
  allow_failures:
    - DJANGO=https://github.com/django/django/archive/master.zip

install:
  - sudo apt-get install libxml2-dev libxslt-dev
  - pip install $DJANGO
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script:
  - cd tests
  - coverage run --source=django_google_dork --omit=*/migrations/* ./manage.py test

# TODO: only w/ django-1.7 and python-3.3
after_success:
  - coveralls
